[workspace]
members = [
    "crates/consensus",
    "crates/predeploys",
    "crates/util",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["tiljrd"]
