[package]
name = "arb-alloy-consensus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
alloy-rlp = "0.3"
alloy-primitives = "1.3"
thiserror = "2"

[dev-dependencies]
proptest = "1.4.0"
